Update setup.py with latest details
CODAIT/hadoop-yarn-api-python-client pull request #96
Opened 2020-10-31 18:50 UTC by dimon222

Some minor corrections.
This library is no more just plain beta (so respective classifier got removed) + repo got moved to new location, so I updated url.

I don't know if we should touch author's email, I might assume in Pypi it plays a role as way to contact author (?), tho, I don't know if @toidi  is still reachable via it anymore. Even if we decide to change it, don't know what to put there.

2020-10-31 18:59 UTC, toidi commented
Hey @dimon222 ,

Thanks for the update!
That email is no longer active. Feel free to remove/change it.

2020-11-02 02:01 UTC, dimon222 commented
@lresende is there some CODAIT contact mailbox that we could plug there?

2020-11-02 02:54 UTC, lresende commented
We don't have anything specific, but most of us have public e-mails on our profiles but we should always encourage communication via issues.

2020-11-02 03:49 UTC, dimon222 commented
@lresende I see. I have done some reading, in our case we could utilize maintainer & maintainer_email. I've added myself there as last point of contact (but I would assume anyway most people will appear in this repo in "Issues")

2020-11-03 19:22 UTC, kevin-bates commented on setup.py
>      author_email = 'e.iskandarov@corp.mail.ru',
Given @toidi said this email is no longer active, I would suggest it be removed.

2020-11-03 21:40 UTC, kevin-bates approved these changes
Thanks Dmitry.

2020-11-03 23:18 UTC, lresende requested changes
I have some suggestions and will provide it later today or early tomorrow.

2020-11-04 07:02 UTC, toidi commented on setup.py
> +    author_email = None,
in case you retain author_email parameter - you could use my personal email: `eduard.iskandarov@ya.ru`

2020-11-20 04:16 UTC, dimon222 commented
@lresende got any update?

2020-12-02 19:45 UTC, lresende approved these changes

2020-12-02 19:45 UTC, merged